version: '2'
services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile

    environment:
      PORT: "8000"

    volumes:
      # Mount the project into /workspace
      - .:/workspace:cached

    # We need a command that keeps running forever.
    # Otherwise the container would stop, and vs code would close.
    command: /bin/sh -c "while sleep 1000; do :; done"
